ALTER TABLE families ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE families ADD COLUMN IF NOT EXISTS photo_consent BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE families ADD COLUMN IF NOT EXISTS emergency_contact_relationship TEXT;
